packages:
  - "packages/*"
packageExtensions:
  '@corbe30/fortune-excel':
    dependencies:
      lodash: ^4.0.0
      react: ^18.3.1

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - prisma
