import type { DemoCatalogEntry, DemoCategory, DemoMarketing } from "./runtime/replayTypes";

type CatalogInput = DemoMarketing & {
  id: string;
};

function createCatalogEntry({ id, ...marketing }: CatalogInput): DemoCatalogEntry {
  return {
    id,
    marketing,
    preview: {
      workbookName: `${marketing.marketingTitle}数据台账`,
      sheetName: "原始数据",
      columns: ["业务场景", "分析指标", "核查状态", "处理结果"],
      rows: [
        [marketing.category, marketing.marketingTitle, marketing.proofMetric, "已完成"],
        ["AI 操作", "结构化分析", "结果写回", "可复核"],
        ["工作簿", "保留原表结构", "公式可追溯", "已保存"],
      ],
    },
  };
}

export const demoCatalog: DemoCatalogEntry[] = [
  createCatalogEntry({
    id: "student-fee-reconciliation",
    category: "财务",
    marketingTitle: "学费住宿费欠费核查",
    summary: "自动匹配学生、收费标准、缴费流水和减免记录，识别欠费、重复缴费与学籍状态异常。",
    coverImage: "/demo-covers/student-fee-reconciliation.webp",
    coverAlt: "学生经过北京一所大学的校园入口",
    proofMetric: "四表匹配 · 5 项待处理",
    featuredOrder: 1,
    theme: "sage",
  }),
  createCatalogEntry({
    id: "research-fund-execution",
    category: "财务",
    marketingTitle: "科研经费预算执行分析",
    summary: "穿透项目预算、报销明细与预算调整，识别超预算、执行偏快和临近结项执行不足。",
    coverImage: "/demo-covers/research-fund-execution.webp",
    coverAlt: "大学生在实验室共同开展科研实验",
    proofMetric: "36 个项目 · 216 笔支出 · 18 项预警",
    featuredOrder: 2,
    theme: "slate",
  }),
  createCatalogEntry({
    id: "school-procurement-audit",
    category: "财务",
    marketingTitle: "采购合同与付款进度核查",
    summary: "贯通采购合同、付款单与验收记录，定位超付、未验收付款、进度倒挂和逾期履约。",
    coverImage: "/demo-covers/school-procurement-audit.webp",
    coverAlt: "采购人员在办公桌前共同审阅合同文件",
    proofMetric: "48 份合同 · 240 条业务记录 · 12 项风险",
    featuredOrder: 3,
    theme: "sand",
  }),
  createCatalogEntry({
    id: "department-budget-monitoring",
    category: "财务",
    marketingTitle: "学校预算执行与部门经费预警",
    summary: "汇总部门预算、月度支出和待支付事项，提前发现资金缺口与执行进度异常。",
    coverImage: "/demo-covers/department-budget-monitoring.webp",
    coverAlt: "财务人员使用计算器核对预算报表",
    proofMetric: "36 个部门 · 306 条业务记录 · 9 项预警",
    featuredOrder: 4,
    theme: "sage",
  }),
  createCatalogEntry({
    id: "student-aid-disbursement",
    category: "财务",
    marketingTitle: "学生资助资金发放核查",
    summary: "匹配资助审批、学籍状态和银行流水，识别重复发放、金额差异、资格异常与漏发。",
    coverImage: "/demo-covers/student-aid-disbursement.webp",
    coverAlt: "大学生携带书本在校园中结伴行走",
    proofMetric: "120 名学生 · 360 条记录 · 16 项异常",
    featuredOrder: 5,
    theme: "sage",
  }),
  createCatalogEntry({
    id: "financial-health-analysis",
    category: "财务",
    marketingTitle: "企业财务健康分析",
    summary: "快速发现现金流、利润与偿债风险，把分散报表变成一张可执行的经营诊断。",
    coverImage: "/demo-covers/financial-health.webp",
    coverAlt: "团队在桌面上讨论财务图表和经营数据",
    proofMetric: "5 类核心指标 · 2 项风险",
    featuredOrder: 6,
    theme: "sage",
  }),
  createCatalogEntry({
    id: "bank-transaction-audit",
    category: "财务",
    marketingTitle: "银行流水智能核查",
    summary: "从数百条流水中定位重复、大额、字段缺失和余额不连续，把异常直接写回核查表。",
    coverImage: "/demo-covers/bank-audit.webp",
    coverAlt: "财务人员使用计算器核对账单和现金记录",
    proofMetric: "4 类异常 · 自动复核",
    featuredOrder: 7,
    theme: "sand",
  }),
  createCatalogEntry({
    id: "sales-performance-analysis",
    category: "销售",
    marketingTitle: "销售业绩分析",
    summary: "对比区域、人员和产品表现，找出增长机会、业绩短板与下一步跟进动作。",
    coverImage: "/demo-covers/sales-performance.webp",
    coverAlt: "销售团队围桌讨论本月业绩",
    proofMetric: "5 个区域 · 6 条行动建议",
    featuredOrder: 8,
    theme: "slate",
  }),
  createCatalogEntry({
    id: "marketing-roi-analysis",
    category: "销售",
    marketingTitle: "营销 ROI 分析",
    summary: "贯通投放、线索、订单和收入，判断哪些渠道真正带来回报，哪些预算应该收缩。",
    coverImage: "/demo-covers/marketing-roi.webp",
    coverAlt: "桌面上的营销图表、笔记本和分析工具",
    proofMetric: "5 个渠道 · ROI 4.22",
    featuredOrder: 9,
    theme: "sage",
  }),
  createCatalogEntry({
    id: "order-fulfillment-analysis",
    category: "运营",
    marketingTitle: "订单履约分析",
    summary: "沿着创建、发货、交付和回款全流程，定位延期、缺货、未回款与低毛利订单。",
    coverImage: "/demo-covers/order-fulfillment.webp",
    coverAlt: "整齐排列货物与纸箱的仓库通道",
    proofMetric: "全流程追踪 · 4 类预警",
    featuredOrder: 10,
    theme: "sand",
  }),
  createCatalogEntry({
    id: "logistics-operations-analysis",
    category: "运营",
    marketingTitle: "物流运营分析",
    summary: "分析线路时效、运输成本和异常签收，在同一张表里发现需要优先治理的路线。",
    coverImage: "/demo-covers/logistics-operations.webp",
    coverAlt: "物流园区中排列整齐的货运卡车",
    proofMetric: "6 条线路 · 准时率诊断",
    featuredOrder: 11,
    theme: "slate",
  }),
  createCatalogEntry({
    id: "investment-budget-review",
    category: "财务",
    marketingTitle: "投资预算审查",
    summary: "逐项重算工程预算和资金来源，识别超预算项目、账面差异与资金缺口。",
    coverImage: "/demo-covers/investment-budget.webp",
    coverAlt: "工程人员在施工现场讨论项目计划",
    proofMetric: "6 个项目 · 逐项重算",
    featuredOrder: 12,
    theme: "sand",
  }),
  createCatalogEntry({
    id: "shareholder-change-analysis",
    category: "财务",
    marketingTitle: "股东变更分析",
    summary: "自动匹配两期股东名册，还原新进、退出、增持和减持，以及股权集中度变化。",
    coverImage: "/demo-covers/shareholder-change.webp",
    coverAlt: "商务团队在会议桌旁分析企业资料",
    proofMetric: "两期名册 · 4 类变动",
    featuredOrder: 13,
    theme: "slate",
  }),
  createCatalogEntry({
    id: "campus-recruitment-analysis",
    category: "人力",
    marketingTitle: "校园招聘分析",
    summary: "比较渠道、岗位和候选人漏斗，找到高效来源与简历、笔试、面试中的流失环节。",
    coverImage: "/demo-covers/campus-recruitment.webp",
    coverAlt: "招聘人员与候选人在办公室进行面试",
    proofMetric: "5 个渠道 · 6 层漏斗",
    featuredOrder: 14,
    theme: "sage",
  }),
  createCatalogEntry({
    id: "exam-score-analysis",
    category: "教育",
    marketingTitle: "考试成绩分析",
    summary: "对比多次考试趋势，找出持续进步、明显下滑和每位学生最需要补强的科目。",
    coverImage: "/demo-covers/exam-score.webp",
    coverAlt: "学生在自然光照射的教室中专注参加考试",
    proofMetric: "3 次考试 · 个性化建议",
    featuredOrder: 15,
    theme: "sand",
  }),
  createCatalogEntry({
    id: "inventory-reconciliation",
    category: "运营",
    marketingTitle: "进销存智能核对",
    summary: "匹配进货、销售和库存数据，检查数量差异、缺货与滞销商品，并保留可复核公式。",
    coverImage: "/demo-covers/inventory.webp",
    coverAlt: "仓储人员在工业货架之间进行库存盘点",
    proofMetric: "三表匹配 · 公式可追溯",
    featuredOrder: 16,
    theme: "slate",
  }),
];

export const demoCatalogById = new Map(demoCatalog.map((demo) => [demo.id, demo]));

export const demoCategories: Array<DemoCategory | "全部"> = [
  "全部",
  "财务",
  "销售",
  "运营",
  "人力",
  "教育",
];
