import { createAnalysisScenario, demoCell, demoRow, resultCell } from "../scenarioFactory";

const money = (value: number) => demoCell(value, { numberFormat: "#,##0.00" });

export const orderFulfillmentAnalysisDemo = createAnalysisScenario({
  id: "order-fulfillment-analysis",
  workspaceId: -160,
  workspaceName: "订单管理演示",
  sessionName: "订单履约风险分析 Demo",
  prompt:
    "请分析订单从创建、发货、交付到回款的全流程，识别延期发货、逾期交付、未回款和低毛利订单，生成订单风险清单并给出跟进建议。",
  workbookName: "制造企业订单台账",
  sourceSheets: [
    {
      name: "订单台账",
      columns: [
        "订单号",
        "客户",
        "订单金额",
        "毛利率",
        "计划发货日",
        "实际发货日",
        "计划回款日",
        "回款金额",
        "订单状态",
      ],
      rows: [
        demoRow(
          "SO260701",
          "瑞丰设备",
          money(860000),
          demoCell(0.22, { numberFormat: "0.0%" }),
          "07-08",
          "07-08",
          "07-30",
          money(860000),
          "已完成",
        ),
        demoRow(
          "SO260702",
          "海拓工业",
          money(1240000),
          demoCell(0.18, { numberFormat: "0.0%" }),
          "07-09",
          "07-13",
          "08-05",
          money(620000),
          "部分回款",
        ),
        demoRow(
          "SO260703",
          "远达科技",
          money(520000),
          demoCell(0.09, { numberFormat: "0.0%" }),
          "07-10",
          "07-10",
          "07-28",
          money(520000),
          "已完成",
        ),
        demoRow(
          "SO260704",
          "东辰能源",
          money(1780000),
          demoCell(0.25, { numberFormat: "0.0%" }),
          "07-11",
          "未发货",
          "08-12",
          money(0),
          "生产中",
        ),
        demoRow(
          "SO260705",
          "优创系统",
          money(690000),
          demoCell(0.17, { numberFormat: "0.0%" }),
          "07-05",
          "07-06",
          "07-22",
          money(0),
          "已交付",
        ),
        demoRow(
          "SO260706",
          "华岭建设",
          money(930000),
          demoCell(0.21, { numberFormat: "0.0%" }),
          "07-15",
          "07-15",
          "08-20",
          money(300000),
          "部分回款",
        ),
        demoRow(
          "SO260707",
          "南山材料",
          money(410000),
          demoCell(0.12, { numberFormat: "0.0%" }),
          "07-12",
          "07-18",
          "08-02",
          money(0),
          "运输中",
        ),
        demoRow(
          "SO260708",
          "景程自动化",
          money(1150000),
          demoCell(0.24, { numberFormat: "0.0%" }),
          "07-18",
          "07-18",
          "08-25",
          money(0),
          "已发货",
        ),
      ],
    },
    {
      name: "客户信用",
      columns: ["客户", "信用等级", "账期上限（天）", "历史逾期次数"],
      rows: [
        demoRow("海拓工业", "B", 30, 2),
        demoRow("东辰能源", "A", 45, 0),
        demoRow("优创系统", "C", 20, 4),
        demoRow("华岭建设", "B", 45, 1),
        demoRow("南山材料", "B", 30, 1),
      ],
    },
  ],
  resultSheet: {
    name: "订单风险清单",
    columns: ["订单号", "客户", "风险类型", "风险金额", "风险等级", "跟进建议"],
    rows: [
      demoRow(
        "SO260702",
        "海拓工业",
        "发货延期4天且仅回款50%",
        money(620000),
        resultCell("高", "danger"),
        "锁定尾款计划并复核客户信用",
      ),
      demoRow(
        "SO260703",
        "远达科技",
        "毛利率仅9%",
        money(520000),
        resultCell("中", "warning"),
        "复盘报价和采购成本",
      ),
      demoRow(
        "SO260704",
        "东辰能源",
        "已过计划发货日仍未发货",
        money(1780000),
        resultCell("高", "danger"),
        "升级生产排期并通知客户",
      ),
      demoRow(
        "SO260705",
        "优创系统",
        "交付后逾期未回款",
        money(690000),
        resultCell("高", "danger"),
        "暂停新增授信并立即催收",
      ),
      demoRow(
        "SO260707",
        "南山材料",
        "发货延期6天",
        money(410000),
        resultCell("中", "warning"),
        "追踪运输节点并评估违约责任",
      ),
    ],
  },
  analysisSteps: [
    {
      id: "read-order-ledger",
      title: "读取订单全流程",
      assistantText: "我先读取订单台账，统一检查计划与实际发货、交付状态、回款金额和毛利率。",
      toolInput: "读取「订单台账」A1:I9，识别履约、回款和利润字段",
      toolOutput: "读取 8 笔订单，总金额 7,580,000 元；已完成 2 笔，其余处于履约或回款阶段",
      activeSheet: "订单台账",
      highlight: "A1:I9",
    },
    {
      id: "detect-fulfillment-risks",
      title: "识别履约风险",
      assistantText:
        "发现三笔发货异常：海拓工业和南山材料分别延期 4 天、6 天；东辰能源订单已过计划发货日但仍未发货。",
      toolInput: "比较计划发货日和实际发货日，定位延期和未发货订单",
      toolOutput: "延期发货 2 笔，逾期未发货 1 笔；涉及订单金额 3,430,000 元",
      activeSheet: "订单台账",
      highlight: "A2:F9",
    },
    {
      id: "review-payment-credit",
      title: "核查回款与信用",
      assistantText:
        "结合客户信用记录，优创系统已经交付但逾期未回款且历史逾期 4 次，应列为高风险；另有一笔订单毛利率低于 10%。",
      toolInput: "关联「客户信用」并检查回款缺口、历史逾期和低毛利订单",
      toolOutput: "高风险回款 2 笔；低毛利订单 1 笔；优创系统信用等级 C 且历史逾期 4 次",
      activeSheet: "客户信用",
      highlight: "A1:D6",
      toolExecutionDuration: 860,
    },
  ],
  writeTitle: "生成订单风险清单",
  writeAssistantText:
    "我已把延期、未发货、逾期回款和低毛利订单整理为风险清单，并给出逐单跟进动作。",
  writeToolInput: "将 5 笔风险订单写入「订单风险清单」A2:F6",
  writeToolOutput: "写入 5 笔风险订单，其中高风险 3 笔、中风险 2 笔",
  verifyAssistantText:
    "复核完成，风险订单均可追溯到订单台账和客户信用表，风险金额与未回款或订单金额一致。",
  verifyToolOutput: "5 笔风险订单全部匹配；高风险 3 笔、中风险 2 笔",
  finalText:
    "订单履约分析完成：建议优先处理东辰能源未发货和优创系统逾期回款，同时跟进海拓尾款，并对低毛利订单复盘报价。",
});
